/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Completions
         * @description Proxy chat completions to the inference backend.
         */
        post: operations["chat_completions_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description List available models from the local manifest file.
         */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description System health check — no auth required.
         */
        get: operations["health_check_vault_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description List all conversations, sorted by most recently updated.
         */
        get: operations["list_conversations_vault_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Create a new conversation.
         */
        post: operations["create_conversation_vault_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Get a conversation with all its messages.
         */
        get: operations["get_conversation_vault_conversations__conversation_id__get"];
        /**
         * Update Conversation
         * @description Update conversation title.
         */
        put: operations["update_conversation_vault_conversations__conversation_id__put"];
        post?: never;
        /**
         * Delete Conversation
         * @description Delete a conversation and all its messages.
         */
        delete: operations["delete_conversation_vault_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Message
         * @description Add a message to a conversation.
         */
        post: operations["add_message_vault_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/training/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Training Jobs
         * @description List all training jobs.
         */
        get: operations["list_training_jobs_vault_training_jobs_get"];
        put?: never;
        /**
         * Create Training Job
         * @description Create a new training job.
         */
        post: operations["create_training_job_vault_training_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/training/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Training Job
         * @description Get training job details.
         */
        get: operations["get_training_job_vault_training_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Training Job
         * @description Delete a training job record.
         */
        delete: operations["delete_training_job_vault_training_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/training/jobs/{job_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Training Job
         * @description Pause a running training job.
         */
        post: operations["pause_training_job_vault_training_jobs__job_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/training/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Training Job
         * @description Resume a paused training job.
         */
        post: operations["resume_training_job_vault_training_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/training/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Training Job
         * @description Cancel a training job.
         */
        post: operations["cancel_training_job_vault_training_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_vault_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_vault_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update User */
        put: operations["update_user_vault_admin_users__user_id__put"];
        post?: never;
        /** Deactivate User */
        delete: operations["deactivate_user_vault_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Keys */
        get: operations["list_keys_vault_admin_keys_get"];
        put?: never;
        /** Create Key */
        post: operations["create_key_vault_admin_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/admin/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Key */
        delete: operations["revoke_key_vault_admin_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/admin/config/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Network Config */
        get: operations["get_network_config_vault_admin_config_network_get"];
        /** Update Network Config */
        put: operations["update_network_config_vault_admin_config_network_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/admin/config/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Settings */
        get: operations["get_system_settings_vault_admin_config_system_get"];
        /** Update System Settings */
        put: operations["update_system_settings_vault_admin_config_system_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/system/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Resources
         * @description CPU, RAM, disk, network, and temperature metrics.
         */
        get: operations["system_resources_vault_system_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/system/gpu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System Gpu
         * @description Per-GPU metrics. Returns empty list if no NVIDIA GPUs detected.
         */
        get: operations["system_gpu_vault_system_gpu_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Insights
         * @description Aggregated usage analytics from the audit log.
         */
        get: operations["insights_vault_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vault/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Activity
         * @description Recent activity feed from the audit log.
         */
        get: operations["activity_vault_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityFeed */
        ActivityFeed: {
            /** Items */
            items: components["schemas"]["ActivityItem"][];
            /** Total */
            total: number;
        };
        /** ActivityItem */
        ActivityItem: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Timestamp */
            timestamp: string;
            /** User */
            user?: string | null;
        };
        /** ChatCompletionRequest */
        ChatCompletionRequest: {
            /** Model */
            model: string;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /** Max Tokens */
            max_tokens?: number | null;
            /**
             * Top P
             * @default 1
             */
            top_p: number;
            /** Stop */
            stop?: string | string[] | null;
        };
        /** ChatMessage */
        ChatMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "system" | "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /**
             * Title
             * @default New Conversation
             */
            title: string;
            /** Model Id */
            model_id: string;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model Id */
            model_id: string;
            /** Messages */
            messages: components["schemas"]["MessageResponse"][];
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Model Id */
            model_id: string;
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** ConversationUpdate */
        ConversationUpdate: {
            /** Title */
            title?: string | null;
        };
        /** GpuDetail */
        GpuDetail: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Memory Total Mb */
            memory_total_mb: number;
            /** Memory Used Mb */
            memory_used_mb: number;
            /** Utilization Pct */
            utilization_pct: number;
            /** Temperature Celsius */
            temperature_celsius?: number | null;
            /** Power Draw Watts */
            power_draw_watts?: number | null;
        };
        /** GpuInfo */
        GpuInfo: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            /** Memory Total Mb */
            memory_total_mb: number;
            /** Memory Used Mb */
            memory_used_mb: number;
            /** Utilization Pct */
            utilization_pct: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Vllm Status */
            vllm_status: string;
            /**
             * Gpu Count
             * @default 0
             */
            gpu_count: number;
            /**
             * Gpus
             * @default []
             */
            gpus: components["schemas"]["GpuInfo"][];
            /**
             * Uptime Seconds
             * @default 0
             */
            uptime_seconds: number;
            /**
             * Version
             * @default 0.1.0
             */
            version: string;
        };
        /** InsightsResponse */
        InsightsResponse: {
            /** Usage History */
            usage_history: components["schemas"]["UsageDataPoint"][];
            /** Response Time Distribution */
            response_time_distribution: components["schemas"]["ResponseTimeDistribution"][];
            /** Model Usage */
            model_usage: components["schemas"]["ModelUsageStats"][];
            /** Total Requests */
            total_requests: number;
            /** Total Tokens */
            total_tokens: number;
            /** Avg Response Time */
            avg_response_time: number;
            /** Active Users */
            active_users: number;
        };
        /** KeyCreate */
        KeyCreate: {
            /** Label */
            label: string;
            /**
             * Scope
             * @default user
             */
            scope: string;
            /** Notes */
            notes?: string | null;
        };
        /** KeyCreateResponse */
        KeyCreateResponse: {
            /** Key */
            key: string;
            /** Id */
            id: number;
            /** Key Prefix */
            key_prefix: string;
            /** Label */
            label: string;
            /** Scope */
            scope: string;
        };
        /** KeyResponse */
        KeyResponse: {
            /** Id */
            id: number;
            /** Key Prefix */
            key_prefix: string;
            /** Label */
            label: string;
            /** Scope */
            scope: string;
            /** Is Active */
            is_active: boolean;
            /** Created At */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** MessageCreate */
        MessageCreate: {
            /**
             * Role
             * @description Message role: user, assistant, or system
             */
            role: string;
            /** Content */
            content: string;
            /** Thinking Content */
            thinking_content?: string | null;
            /** Thinking Duration Ms */
            thinking_duration_ms?: number | null;
        };
        /** MessageResponse */
        MessageResponse: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Timestamp */
            timestamp: number;
            /** Thinking */
            thinking?: {
                [key: string]: unknown;
            } | null;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Parameters */
            parameters?: string | null;
            /** Quantization */
            quantization?: string | null;
            /** Context Window */
            context_window?: number | null;
            /** Vram Required Gb */
            vram_required_gb?: number | null;
            /** Description */
            description?: string | null;
        };
        /** ModelListResponse */
        ModelListResponse: {
            /**
             * Object
             * @default list
             */
            object: string;
            /** Data */
            data: components["schemas"]["ModelInfo"][];
        };
        /** ModelUsageStats */
        ModelUsageStats: {
            /** Model */
            model: string;
            /** Requests */
            requests: number;
            /** Percentage */
            percentage: number;
        };
        /** NetworkConfigResponse */
        NetworkConfigResponse: {
            /** Hostname */
            hostname: string;
            /** Ip Address */
            ip_address: string;
            /** Subnet Mask */
            subnet_mask: string;
            /** Gateway */
            gateway: string;
            /** Dns Servers */
            dns_servers: string[];
            /** Network Mode */
            network_mode: string;
        };
        /** NetworkConfigUpdate */
        NetworkConfigUpdate: {
            /** Hostname */
            hostname?: string | null;
            /** Dns Servers */
            dns_servers?: string[] | null;
        };
        /** ResourceAllocation */
        ResourceAllocation: {
            /**
             * Gpu Count
             * @default 1
             */
            gpu_count: number;
            /**
             * Gpu Memory
             * @default 24GB
             */
            gpu_memory: string;
            /** Estimated Time */
            estimated_time?: string | null;
            /** Actual Time */
            actual_time?: string | null;
        };
        /** ResponseTimeDistribution */
        ResponseTimeDistribution: {
            /** Range */
            range: string;
            /** Count */
            count: number;
        };
        /** SystemResources */
        SystemResources: {
            /** Cpu Usage Pct */
            cpu_usage_pct: number;
            /** Cpu Count */
            cpu_count: number;
            /** Ram Total Mb */
            ram_total_mb: number;
            /** Ram Used Mb */
            ram_used_mb: number;
            /** Ram Usage Pct */
            ram_usage_pct: number;
            /** Disk Total Gb */
            disk_total_gb: number;
            /** Disk Used Gb */
            disk_used_gb: number;
            /** Disk Usage Pct */
            disk_usage_pct: number;
            /** Network In Bytes */
            network_in_bytes: number;
            /** Network Out Bytes */
            network_out_bytes: number;
            /** Temperature Celsius */
            temperature_celsius?: number | null;
        };
        /** SystemSettingsResponse */
        SystemSettingsResponse: {
            /** Timezone */
            timezone: string;
            /** Language */
            language: string;
            /** Auto Update */
            auto_update: boolean;
            /** Telemetry */
            telemetry: boolean;
            /** Session Timeout */
            session_timeout: number;
            /** Max Upload Size */
            max_upload_size: number;
            /** Debug Logging */
            debug_logging: boolean;
            /** Diagnostics Enabled */
            diagnostics_enabled: boolean;
        };
        /** SystemSettingsUpdate */
        SystemSettingsUpdate: {
            /** Timezone */
            timezone?: string | null;
            /** Language */
            language?: string | null;
            /** Auto Update */
            auto_update?: boolean | null;
            /** Telemetry */
            telemetry?: boolean | null;
            /** Session Timeout */
            session_timeout?: number | null;
            /** Max Upload Size */
            max_upload_size?: number | null;
            /** Debug Logging */
            debug_logging?: boolean | null;
            /** Diagnostics Enabled */
            diagnostics_enabled?: boolean | null;
        };
        /**
         * TimeRange
         * @enum {string}
         */
        TimeRange: "24h" | "7d" | "30d" | "90d";
        /** TrainingConfig */
        TrainingConfig: {
            /**
             * Epochs
             * @default 10
             */
            epochs: number;
            /**
             * Batch Size
             * @default 32
             */
            batch_size: number;
            /**
             * Learning Rate
             * @default 0.0001
             */
            learning_rate: number;
            /**
             * Warmup Steps
             * @default 100
             */
            warmup_steps: number;
            /**
             * Weight Decay
             * @default 0.01
             */
            weight_decay: number;
            /**
             * Optimizer
             * @default adamw
             */
            optimizer: string;
            /**
             * Scheduler
             * @default cosine
             */
            scheduler: string;
        };
        /** TrainingJobCreate */
        TrainingJobCreate: {
            /** Name */
            name: string;
            /** Model */
            model: string;
            /** Dataset */
            dataset: string;
            /**
             * @default {
             *       "epochs": 10,
             *       "batch_size": 32,
             *       "learning_rate": 0.0001,
             *       "warmup_steps": 100,
             *       "weight_decay": 0.01,
             *       "optimizer": "adamw",
             *       "scheduler": "cosine"
             *     }
             */
            config: components["schemas"]["TrainingConfig"];
            /**
             * @default {
             *       "gpu_count": 1,
             *       "gpu_memory": "24GB"
             *     }
             */
            resource_allocation: components["schemas"]["ResourceAllocation"];
        };
        /** TrainingJobList */
        TrainingJobList: {
            /** Jobs */
            jobs: components["schemas"]["TrainingJobResponse"][];
            /** Total */
            total: number;
        };
        /** TrainingJobResponse */
        TrainingJobResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Model */
            model: string;
            /** Dataset */
            dataset: string;
            config: components["schemas"]["TrainingConfig"];
            metrics: components["schemas"]["TrainingMetrics"];
            resource_allocation: components["schemas"]["ResourceAllocation"];
            /** Error */
            error?: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Created At */
            created_at: string;
        };
        /** TrainingMetrics */
        TrainingMetrics: {
            /** Loss */
            loss?: number | null;
            /** Accuracy */
            accuracy?: number | null;
            /** Learning Rate */
            learning_rate?: number | null;
            /**
             * Epochs Completed
             * @default 0
             */
            epochs_completed: number;
            /**
             * Total Epochs
             * @default 0
             */
            total_epochs: number;
            /**
             * Tokens Processed
             * @default 0
             */
            tokens_processed: number;
            /** Estimated Time Remaining */
            estimated_time_remaining?: string | null;
        };
        /** UsageDataPoint */
        UsageDataPoint: {
            /** Date */
            date: string;
            /** Requests */
            requests: number;
            /** Tokens */
            tokens: number;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Role
             * @default user
             */
            role: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Last Active */
            last_active: string | null;
            /**
             * Api Key Count
             * @default 0
             */
            api_key_count: number;
            /** Created At */
            created_at: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat_completions_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListResponse"];
                };
            };
        };
    };
    health_check_vault_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_conversations_vault_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_vault_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_vault_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_vault_conversations__conversation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_vault_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_vault_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_training_jobs_vault_training_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobList"];
                };
            };
        };
    };
    create_training_job_vault_training_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_training_job_vault_training_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_training_job_vault_training_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_training_job_vault_training_jobs__job_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_training_job_vault_training_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_training_job_vault_training_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrainingJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_vault_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create_user_vault_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_vault_admin_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_vault_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_vault_admin_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyResponse"][];
                };
            };
        };
    };
    create_key_vault_admin_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_key_vault_admin_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_network_config_vault_admin_config_network_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkConfigResponse"];
                };
            };
        };
    };
    update_network_config_vault_admin_config_network_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_settings_vault_admin_config_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingsResponse"];
                };
            };
        };
    };
    update_system_settings_vault_admin_config_system_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_resources_vault_system_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemResources"];
                };
            };
        };
    };
    system_gpu_vault_system_gpu_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuDetail"][];
                };
            };
        };
    };
    insights_vault_insights_get: {
        parameters: {
            query?: {
                range?: components["schemas"]["TimeRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activity_vault_activity_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityFeed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
